services:
  jupyter:
    image: franzdiebold/datascience-ultimate:latest
    ports:
      - 8888:8888
    volumes:
      - .:/usr/src/advent-of-code-solver
    working_dir: /usr/src/advent-of-code-solver
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
